export { Navigation } from "./Navigation"
export { Hero } from "./Hero"
export { PhoneMockup } from "./PhoneMockup"
export { Features } from "./Features"
export { HowItWorks } from "./HowItWorks"
export { Loyalty } from "./Loyalty"
export { Rules } from "./Rules"
export { CTA } from "./CTA"
export { Footer } from "./Footer"

